### ISSUE TITLE
Convert glyph outlined path to single line bezier path #12

### ISSUE THREAD

**Issue by alyfreym** [inanevin/LinaVG#2]
Hi its possible using this lib convert outlined glyph path to single line path? I pin example image what I mean. Any suggestion please, or article.
![Group 3](https://user-images.githubusercontent.com/29518174/202890096-6211b1bf-724b-4fc1-b01e-61426ebc09ab.png)

**Comment by inanevin** [comment]
Unfortunately LinaVG supports no such operation. I suggest taking a look at FreeType library for learning more about glyph paths and possible conversions.
