### ISSUE TITLE
Can't build, no _Dependencies folder

### ISSUE THREAD

**Issue by ryuukk** [inanevin/LinaVG#3]
_Dependencies folder is missing

**Comment by inanevin** [comment]
How are you trying to build the project? When you use the CMakeLists.txt file in the root directory, it should download the dependency repository.

**Comment by inanevin** [comment]
Visual Studio's CMake integration is problematic afaik. I would suggest using CMake GUI to generate the project files. Using that, it should start the download for the _Dependencies folder.
