### ISSUE TITLE
Please support MSYS2 MINGW64

### ISSUE THREAD

**Issue by ghost** [inanevin/LinaVG#7]

**Comment by inanevin** [comment]
Support will be added along with support for Clang and GCC. I can't give an exact estimate atm but I will try to get it done before 2023 Q3.

**Comment by inanevin** [comment]
Entered Q3, I thought I'll give a little update. Currently Clang support is handled, I am as well testing OSX support. Next update will include this, just a little more time :).

**Comment by inanevin** [comment]
Now should be able to compile using MSVC, Clang and GCC. You can ofc. make use of CMake to generate MinGW makefiles or MSYS Makefiles. Please report issues separately if you are facing compilation errors.
